# permissions for end users to view tektonobservations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tektonobservation-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tekton-observer
    app.kubernetes.io/part-of: tekton-observer
    app.kubernetes.io/managed-by: kustomize
  name: tektonobservation-viewer-role
rules:
- apiGroups:
  - observer.tkn.dev
  resources:
  - tektonobservations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - observer.tkn.dev
  resources:
  - tektonobservations/status
  verbs:
  - get
